apiVersion: harness.io/v1
kind: component

name: first-component
identifier: firstcomponent

projectIdentifier: TEST
orgIdentifier: default

type: service

owner: group:account/_account_all_users

spec:
  lifecycle: development

  sourceCode:
    provider: Github
    repoName: UpSklling
    connectorRef: account.newconnector
    branch: main
    monoRepo: false

metadata:
  description: First IDP Component
  tags:
    - demo